##############  Screen  ##############

WINDOW_WIDTH = 670
WINDOW_HEIGHT = 670
INDENT = 50
HALF_INDENT = INDENT // 2
MAP_WIDTH = WINDOW_WIDTH - INDENT
MAP_HEIGHT = WINDOW_WIDTH - INDENT
COLUMNS = 31
ROWS = 31
SQUARE_WIDTH = MAP_WIDTH // COLUMNS
SQUARE_HEIGHT = MAP_HEIGHT // ROWS
X_LINE = WINDOW_WIDTH // SQUARE_WIDTH
Y_LINE = WINDOW_HEIGHT // SQUARE_HEIGHT
FPS = 60

##############  Colors  ##############

PACMAN_COLOR = (193, 191, 12)
WALL_COLOR = (188,143,143)
POINT_COLOR = (148,0,211)
LINES_COLOR = (105, 105, 105)
BACKGROUND_COLOR = (0, 0, 0)
TEXT_COLOR = (255, 255, 255)

##############  Fonts  ##############

TEXT_SIZE = 16
FONT = 'arial black'